# Generated by Django 4.2.3 on 2023-08-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_creator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
