# Generated by Django 4.2.3 on 2023-08-03 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_creator', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
