# Generated by Django 4.2.3 on 2023-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_creator', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
